const PRODUCTS = [
  {
    id: 1,
    name: "OFW Financial Freedom Planner",
    category: "Digital",
    price: 299,
    currency: "PHP",
    description: "A printable & digital planner designed for OFWs — budget tracker, remittance log, investment tracker, and balik-bayan goal planner.",
    icon: "📓",
    badge: "Bestseller",
  },
  {
    id: 2,
    name: "Millionaire Mindset E-Book",
    category: "Digital",
    price: 199,
    currency: "PHP",
    description: "The complete guide to building wealth as an OFW. Covers mindset, saving, investing, and building passive income from abroad.",
    icon: "📖",
    badge: "New",
  },
  {
    id: 3,
    name: "Premium Health Supplement Pack",
    category: "Health",
    price: 1500,
    currency: "PHP",
    description: "High-quality supplements to keep you strong and healthy while working abroad. Immune support, energy boost, and vitamins in one pack.",
    icon: "💊",
    badge: "",
  },
  {
    id: 4,
    name: "OFW Investment Starter Kit",
    category: "Digital",
    price: 499,
    currency: "PHP",
    description: "Step-by-step guide + templates to open your first Philippine stock, UITF, and savings account from abroad. Includes video tutorials.",
    icon: "📈",
    badge: "",
  },
  {
    id: 5,
    name: "Skincare & Wellness Bundle",
    category: "Health",
    price: 2200,
    currency: "PHP",
    description: "Premium skincare products perfect for harsh weather conditions abroad. All-natural ingredients, dermatologist-tested.",
    icon: "✨",
    badge: "Hot",
  },
  {
    id: 6,
    name: "Family Budget Masterclass",
    category: "Course",
    price: 799,
    currency: "PHP",
    description: "Online video course teaching your family back home how to manage remittances, avoid debt, and save for the future.",
    icon: "🎓",
    badge: "",
  },
];
